apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mysql
    owner: Eshakita
  name: mysql-pvc
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi