apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  labels:
    app: phpmyadmin
    owner: Eshakita
  annotations:
    metallb.universe.tf/allow-shared-ip: default
spec:
  selector:
    app: phpmyadmin
  type: LoadBalancer
  loadBalancerIP: 192.168.99.128
  ports:
      - protocol: TCP
        name: phpmyadmin
        port: 5000
        targetPort: 5000